**Política $R_{a}$**: Costo Promedio Estimado a Largo Plazo

In [ ]:
import numpy as np

A = np.array([[-1, 0, 0, 1],
              [1/16, 1/8, -1/2, 0],
              [1/16, 1/8, 1/2, -1],
              [1, 1, 1, 1]])

B = np.array([0, 0, 0, 1])
X = np.linalg.inv(A).dot(B)

print(X)

[0.15384615 0.53846154 0.15384615 0.15384615]


**Política $R_{b}$**: Costo Promedio Estimado a Largo Plazo

In [ ]:
import numpy as np

A = np.array([[-1, 0, 0, 1],
              [7/8, -1/4, 1, 0],
              [1/16, 1/8, -1, 0],
              [1, 1, 1, 1]])

B = np.array([0, 0, 0, 1])
X = np.linalg.inv(A).dot(B)

print(X)

[0.0952381  0.71428571 0.0952381  0.0952381 ]


**Política $R_{c}$**: Costo Promedio Estimado a Largo Plazo

In [ ]:
import numpy as np

A = np.array([[-1, 0, 1, 1],
              [7/8, -1/4, 0, 0],
              [1/16, 1/8, -1, 0],
              [1, 1, 1, 1]])

B = np.array([0, 0, 0, 1])
X = np.linalg.inv(A).dot(B)

print(X)

[0.18181818 0.63636364 0.09090909 0.09090909]


**Política $R_{d}$**: Costo Promedio Estimado a Largo Plazo

In [ ]:
import numpy as np

A = np.array([[-1, 1, 1, 1],
              [7/8, -1, 0, 0],
              [1/16, 0, -1, 0],
              [1, 1, 1, 1]])

B = np.array([0, 0, 0, 1])
X = np.linalg.inv(A).dot(B)

print(X)

[0.5     0.4375  0.03125 0.03125]
