Para la politica $R_1$

In [3]:
import numpy as np

A = np.array([[-1/2, 3/10, 0],
              [1/2, -1/2, 3/5],
              [1, 1, 1]])

B = np.array([0, 0, 1])
X = np.linalg.inv(A).dot(B)

print(X)

[0.31034483 0.51724138 0.17241379]


Para la política $R_2$:

In [7]:
import numpy as np

A = np.array([[-1/2, 3/10, 0],
              [1/2, -1/2, 4/5],
              [1, 1, 1]])

B = np.array([0, 0, 1])
X = np.linalg.inv(A).dot(B)

print(X)

[0.32432432 0.54054054 0.13513514]


Para la política $R_3$:

In [8]:
import numpy as np

A = np.array([[-1/2, 2/5, 0],
              [0, 1/10, -3/5],
              [1, 1, 1]])

B = np.array([0, 0, 1])
X = np.linalg.inv(A).dot(B)

print(X)

[0.40677966 0.50847458 0.08474576]


Para la política $R_4$

In [9]:
import numpy as np

A = np.array([[-1/2, 2/5, 0],
              [1/2, -1/2, 3/5],
              [1, 1, 1]])

B = np.array([0, 0, 1])
X = np.linalg.inv(A).dot(B)

print(X)

[0.40677966 0.50847458 0.08474576]
