**Problema 16.6-4 Hillier Lieberman Novena Edición**

Considere el ejemplo de inventarios de la sección 16.1 pero 
ahora la demanda tiene la siguiente distribución de probabilidad:

*  P{D = 0} = 1/4 
*  P{D = 1} = 1/2
*  P{D = 2} = 1/4
*  P{D ≥ 3} = 0

La política de órdenes cambia al ordenar exactamente dos cámaras al 
final de la semana si el inventario es cero. Como antes, no se ordena si 
hay cámaras en inventario. Suponga que se tiene una cámara (al final 
de la semana) cuando se instituye la política.

**a)** Construya la matriz de transición (de un paso).

**b)** Encuentre la distribución de probabilidad del estado de esta 
cadena de Markov n semanas después de instituir la nueva 
política de inventarios, para n = 2, 5, 10.

**c)** Encuentre las $µ_{ij}$ (el tiempo esperado de primera pasada del estado i al j) para toda i y j.

**d)** Encuentre las probabilidades de estado estable del estado de 
esta cadena de Markov. 

**e)** Bajo el supuesto de que la tienda paga un costo de almacenamiento por cada cámara que queda en la repisa al final de la semana, de acuerdo con la función C(0) = 0, C(1) = \\$2, C(2) = \\$8, encuentre el costo promedio de almacenamiento a largo plazo 
por semana.

**Pregunta (b):**

**Para n = 2:**

In [ ]:
import numpy as np

P = np.array([[0.25, 0.5, 0.25],
              [0.75, 0.25, 0],
              [0.25, 0.5, 0.25]])

P2 = np.linalg.matrix_power(A, 2)

print(P2)

[[0.5    0.375  0.125 ]
 [0.375  0.4375 0.1875]
 [0.5    0.375  0.125 ]]


**Para n = 5:**

Primero calculamos $P^{(4)}$ al realizar los cálculos en el archivo PDF. Se incluye este resultado en el código para verificar el resultado.

In [ ]:
P4 = np.linalg.matrix_power(P, 4)
print(P4)

[[0.453125   0.3984375  0.1484375 ]
 [0.4453125  0.40234375 0.15234375]
 [0.453125   0.3984375  0.1484375 ]]


Luego, obtenemos $P^{(5)}$

In [ ]:
P5 = np.linalg.matrix_power(P, 5)
print(P5)

[[0.44921875 0.40039062 0.15039062]
 [0.45117188 0.39941406 0.14941406]
 [0.44921875 0.40039062 0.15039062]]


**Para n = 10:**

Calculamos $P^{(10)}$

In [ ]:
P10 = np.linalg.matrix_power(P, 10)
print(P10)

[[0.45000076 0.39999962 0.14999962]
 [0.44999886 0.40000057 0.15000057]
 [0.45000076 0.39999962 0.14999962]]
